README.md
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/gnt4/chr/KabutoScalingFix.java
src/main/java/com/github/nicholasmoser/gnt4/chr/KisamePhantomSwordFix.java
src/main/java/com/github/nicholasmoser/gnt4/chr/ZabuzaPhantomSwordFix.java
src/main/resources/com/github/nicholasmoser/gnt4/menu.fxml

There are three things in vanilla GNT4 that are affected by whether or not you are player 1 or player 2. These include:
- Kabuto 2A Scaling for Player 2
- Phantom Sword Only Usable by Kisame Player 1
- Phantom Sword Only Usable by Zabuza Player 1
I have added new fixes to GNTool that will fix all three of these. For more information regarding them see the updated to the README.md.

Fixes for Player 1 vs 2 Specific Behavior

---

README.md
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/gnt4/chr/KabutoScalingFix.java
src/main/java/com/github/nicholasmoser/gnt4/chr/KisamePhantomSwordFix.java
src/main/java/com/github/nicholasmoser/gnt4/chr/ZabuzaPhantomSwordFix.java
src/main/resources/com/github/nicholasmoser/gnt4/menu.fxml

There are a few issues with vanilla relating to player 2.
Player 2 is unable to perform phantom sword for either Zabuza or Kisame. This is an unblockable attack when you land with jumping A within a 1-frame window. I have added new fixes for each character so that player 2 can perform phantom sword as them.
Additional, Kabuto's 2A does unscaled damage as player 1, and scaled damage as player 2. I have added a fix so that 2A does unscaled damage also as player 2.

Fixes for Player 2 Specific Behavior

---

README.md
src/main/java/com/github/nicholasmoser/FPKFileHeader.java
src/main/java/com/github/nicholasmoser/FPKPacker.java
src/main/java/com/github/nicholasmoser/FPKUnpacker.java
src/main/java/com/github/nicholasmoser/ToolController.java
src/main/java/com/github/nicholasmoser/gnt4/GNT4Extractor.java
src/main/java/com/github/nicholasmoser/gnt4/GNT4Files.java
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/tools/FPKRepackerTool.java
src/main/java/com/github/nicholasmoser/tools/FPKUnpackerTool.java
src/main/java/com/github/nicholasmoser/utils/ByteUtils.java
src/main/java/com/github/nicholasmoser/utils/FPKUtils.java
src/main/java/com/github/nicholasmoser/utils/GUIUtils.java
src/main/java/com/github/nicholasmoser/utils/ProtobufUtils.java
src/test/java/com/github/nicholasmoser/ProtoBufCreatorTest.java
src/test/java/com/github/nicholasmoser/utils/ByteUtilsTest.java

There are Eighting titles on the PS2 and PSP that have FPK files. These FPK files are little endian, whereas all GameCube and Wii FPK files are big endian. I have added new tools and logic to GNTool to add support for these little endian FPK files. I also cleaned up the FPK logic to not specify the platform, but rather the endianness and whether paths are short or long (16 vs 32 bytes).

Add Support for Unpacking/Repacking PS2/PSP FPK Files

---

README.md
src/main/java/com/github/nicholasmoser/gnt4/GNT4Codes.java
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/resources/com/github/nicholasmoser/gnt4/menu.fxml

This change adds a new spinner to the main workspace menu titled "Frames Until Model is Loaded in Character Select Screen":
This allows you to change the number of frames before a model is loaded in the character select screen (CSS). In vanilla GNT4 the model for a character will be loaded 60 frames after hovering over the character. The game runs in 60 frames per second, so the default is approximately 1 second. It looks like this:
Loading the model causes the game to freeze for a quick moment, especially so when the game is loaded from your local file system instead of via an ISO/disc. This freeze can resort in a worse quality of life while playing the game. By raising the number of frames, you can make the game wait longer (or basically forever) before it tries to load the model.
Here …

Add spinner to modify frames before CSS models are loaded

---

src/main/java/com/github/nicholasmoser/gnt4/dol/DolHijack.java
src/main/java/com/github/nicholasmoser/utils/HttpUtils.java
src/main/java/module-info.java

This change downloads known codes over HTTP first, and if that fails, falls back to the codes in the JSON file included with GNTool. The purpose of this is to easily add new codes to master and allow consumers to benefit from these codes without needing to download the latest version of GNTool.

Download codes over HTTP

---

src/main/java/com/github/nicholasmoser/FPKPacker.java
src/main/java/com/github/nicholasmoser/Workspace.java
src/main/java/com/github/nicholasmoser/gnt4/GNT4Files.java
src/main/java/com/github/nicholasmoser/gnt4/GNT4Workspace.java
src/test/java/com/github/nicholasmoser/gnt4/GNT4FilesTest.java

Fixes https://github.com/NicholasMoser/GNTool/issues/72
Turns out there are some files in the game that are FPK compressed, but by more than one FPK file. Therefore, when repacking FPK files GNTool must repack each FPK parent that exists.

Fix unpacking of files with more than one FPK parent

---

src/main/java/com/github/nicholasmoser/tools/FPKRepackerTool.java

https://github.com/NicholasMoser/GNTool/issues/74
Adds a button to the FPK repacker allowing you to save the current paths to a template file. Paths not filled out will save out the FPK path instead.
Example:
After saving and loading:

Save Template button added to FPK Repacker

---

src/main/java/com/github/nicholasmoser/gnt4/seq/ext/SeqEditor.java
src/main/java/com/github/nicholasmoser/utils/Ranges.java
src/test/java/com/github/nicholasmoser/utils/RangesTest.java

When adding a SEQ edit in the SEQ editor, it will make sure that any new codes do not overlap existing codes. The logic for checking if two codes are overlapping is incorrect, and this PR fixes that.
Previously it did:
```java
boolean hasNoOverlap = (existingStart <= newEnd) && (existingEnd <= newStart);
```
This fails in some cases such as for the ranges [125220, 125228] and [123592, 123600]
```java
(125220 <= 123600) && (125228 <= 123592) = false
```
Which should be `true` since they have no overlap.
This has been fixed with new logic.

Fix SEQ editor code overlap range comparison

---

src/main/java/com/github/nicholasmoser/gnt4/seq/DolphinSeqListener.java

Made the java.awt.Desktop class calls spin of in a separate system thread so that they won't freeze the application on Linux.
Made a conditional branch depending on operating system to decide how to
open the disassembled seq file in a browser on the correct row.
It works on Linux, please make sure it didn't destroy the experience on Windows

Linux fix for DolphinSeqListener

---

src/main/java/com/github/nicholasmoser/audio/MusyXExtract.java
src/test/java/com/github/nicholasmoser/audio/MustXExtractTest.java
src/test/java/com/github/nicholasmoser/gnt4/seq/SEQRegCMD1Test.java
src/test/java/com/github/nicholasmoser/gnt4/seq/SEQRegCMD2Test.java
src/test/java/com/github/nicholasmoser/tools/ISOCompareToolTest.java

Fix unit tests for Windows and Linux. Windows tests broke from https://github.com/NicholasMoser/GNTool/pull/91 and Linux tests never passed in the first place. By getting Linux tests to pass, [Linux binaries can be released](https://github.com/NicholasMoser/GNTool/issues/89).
- https://github.com/NicholasMoser/GNTool/pull/91 broke the tests in `SEQRegCMD1Test.java` and `SEQRegCMD2Test.java` due to the field offset for `seq_p_sp` changing. This has now been fixed.
- Linux fails `ISOCompareToolTest.java` as it uses `/` as the path separator instead of `\`. This has now been fixed.
- Linux fails `MustXExtractTest.java` as files must be listed in alphabetic order but are instead listed in "random" order. This has now been fixed by always sorting the list of files.

Fix Unit Tests for Windows and Linux

---

src/main/java/com/github/nicholasmoser/gnt4/seq/SEQ_RegCMD1.java
src/main/java/com/github/nicholasmoser/gnt4/seq/SEQ_RegCMD2.java

Noticed that instantiations of SeqOperands from different parts of SEQ_RegCMD were treated differently in offsets. They are all treated the
same in the .dol, just that the order of the subtraction and
multiplication is inverted in some places so that it looks like either
(op - 0x18) * 4
or
op * 4 - 0x60
depending on exact position, but the end result is the same

Fix for instantiation of SeqOperand

---

src/main/java/com/github/nicholasmoser/audio/FFmpeg.java

Uses a variable to store ffmpeg executable name, if system is windows, use ffmpeg.exe, else use ffmpeg.
If not Windows, test if ffmpeg can be executed in runtime, and throw error if it can not be found.

FFmpeg non windows system fix

---

src/main/java/com/github/nicholasmoser/audio/FFmpeg.java
src/main/java/com/github/nicholasmoser/utils/GUIUtils.java
src/test/java/com/github/nicholasmoser/fpk/PRSCompare.java
src/test/java/com/github/nicholasmoser/tools/ISOCompareToolTest.java

Before this PR, `Platform.isWindows()` was being used to check if Windows is the operating system. `Platform.isWindows()` is part of the dependency `jna` which I'd prefer to keep test scope since it currently has no reason to be bundled with GNTool. Therefore, since it's test scope `Platform.isWindows()` cannot be used in the main java code.
This PR adds a method to `GUIUtils` to check if Windows is the running platform in the same way that `jna` checks.

Create isWindows method to use across GNTool

---

src/main/java/com/github/nicholasmoser/mot/BoneAnimation.java
src/main/java/com/github/nicholasmoser/mot/Coordinate.java
src/main/java/com/github/nicholasmoser/mot/GNTAEditor.java
src/main/java/com/github/nicholasmoser/mot/GNTAnimation.java
src/main/resources/com/github/nicholasmoser/mot/motedit.fxml
src/test/java/com/github/nicholasmoser/mot/CoordinateTest.java

This PR adds some additional changes to @Athkore's branch for Rev 3 animation support. Specifically this fixes a few things related to 0x0202 animations (which use shorts) vs 0x0204 animations (which use floats).
- Internally store coordinates as floats. This is necessary to preserve the precision for 0x0204 animations. Previously we used shorts, since GNT4 only uses 0x0202 animations.
- Correctly write floats to files when the animation type is 0x0204.
- Add a setting to the Motion Editor to change 0x0204 animations to 0x0202 animations so that GNT4 can use them.[1]
- Make converting 0x0204 animations to 0x0202 animations optional, and only enabled by the above Motion Editor setting.
- Correctly fix 16-byte alignment when 0x0204 animations are converted to 0x0202 animations.
[1]

Additional Changes for Rev 3 Animation Support

---

src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/gnt4/cpu/CPUFlags.java
src/main/java/com/github/nicholasmoser/gnt4/seq/Seqs.java
src/main/resources/com/github/nicholasmoser/gnt4/menu.fxml
src/test/java/com/github/nicholasmoser/gnt4/cpu/CPUFlagsTest.java

Implements https://github.com/NicholasMoser/GNTool/issues/106
Much like Eighting's other title Bloody Roar, Naruto GNT4 also has recording functionality in its training mode. However in GNT4 this recording functionality is disabled. This pull request allows you to add it back into the game by replacing a training mode CPU option.
First, I've added a button called **Fix Recording Text Size**. It is necessary to press this button at least once to add a new bit field to the DOL to process the recording text with the correct size. Then, like the image above shows, select a CPU option such as **Stand** and **Jump** to replace with **Recording** and **Recording/Counter**.
Recording can be enabled by pressing down on the C-stick. Then you can control your opponent as you wish. When done, press …

Add Recording Functionality

---

src/main/java/com/github/nicholasmoser/gnt4/seq/DolphinSeqListener.java
src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java
src/main/java/com/github/nicholasmoser/gnt4/seq/SeqKing.java
src/main/java/com/github/nicholasmoser/gnt4/seq/opcodes/InvalidBytes.java
src/main/java/com/github/nicholasmoser/tools/SeqDisassemblerTool.java
src/main/java/com/github/nicholasmoser/utils/ByteStream.java
src/test/java/com/github/nicholasmoser/gnt4/seq/SeqKingTest.java

Some mods like SCON4 directly modified the bytes in the SEQ files. Opcodes are variable length, and in some cases these modifications result in broken opcodes (e.g. 4 bytes of an 8 byte opcode were overridden). This will fail to be parsed by the SEQ report disassembler.
This PR adds in the ability to allow SEQ parsing to be permissive. By default, all SEQ parsing initiated by the GUI will be permissive. All SEQ parsing done for unit testing will not be, to make it easier to add support for new opcodes.
Example:

Add permissive SEQ disassembling

---

src/main/resources/com/github/nicholasmoser/gnt4/dol/known_codes.json

When attempting to create a new workspace from an existing ISO with Gecko codes, you will get the following error:
```
SEVERE: Error getting list of applied codes.
org.json.JSONException: JSONArray[15] is not a JSONObject.
at org.json@20220320/org.json.JSONArray.wrongValueFormatException(JSONArray.java:1694)
at org.json@20220320/org.json.JSONArray.getJSONObject(JSONArray.java:481)
at com.github.nicholasmoser@4.3.0-SNAPSHOT/com.github.nicholasmoser.gnt4.dol.DolHijack.findCodeMatch(DolHijack.java:204)
at com.github.nicholasmoser@4.3.0-SNAPSHOT/com.github.nicholasmoser.gnt4.dol.DolHijack.handleActiveCodesButNoCodeFile(DolHijack.java:122)
at com.github.nicholasmoser@4.3.0-SNAPSHOT/com.github.nicholasmoser.gnt4.MenuController.lambda$refreshActiveCodes$17(MenuController.java:1641)
at …
```

Remove extra comma from known_codes.json

---

src/main/java/com/github/nicholasmoser/gecko/GeckoCodeJSON.java
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/iso/ISOCreator.java
src/test/java/com/github/nicholasmoser/iso/DuplicateISOTest.java
src/test/java/com/github/nicholasmoser/iso/FileSystemTableTest.java

This PR fixes two issues.
1. The order of building the ISO causes issues when new files have been added to the workspace. This is because the ISOHeader is created, the file system table is updated, and then the ISO is built. The issue is that updating the file system table changes the size of the file if new files have been added. Therefore the order is now: create the ISOHeader, update the file system table, create a new ISOHeader, then build the ISO. We must create the ISOHeader twice because it is required the first time to update the file system table.
2. When the codes.json exists at the root directory of ISO files, it causes issues in Dolphin. That is, Dolphin fails to read the banner data (`opening.bnr`) which is also stored at the root directory of ISO files.
**Expected** …

Workspace Files Fixes

---

src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/gnt4/seq/comment/Comments.java
src/main/java/com/github/nicholasmoser/gnt4/seq/comment/Functions.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup3C.java
src/main/java/com/github/nicholasmoser/gnt4/ui/CostumeController.java
src/main/java/com/github/nicholasmoser/gnt4/ui/DupeCostumeFix.java
src/main/resources/com/github/nicholasmoser/gnt4/menu.fxml
src/test/java/com/github/nicholasmoser/gnt4/ui/DupeCostumeFixTest.java

The existing code of the game treats costumes 1 and 3 as identical. Same for 2 and 4. It probably does this since the clothes are the same (despite face/hair changing). Also, when the code detects a duplicate costume it goes from costume 1->2, 2->1, 3->4, 4->3.
Both of these behaviors are an issue. Going from 3->4 crashes if there's no costume 4. Also, you can't have costume 1 and 3 fight each other because the game thinks they're duplicates. Same for 2 and 4. I fixed this by writing new code that overwrites the existing behavior. 1 and 3, 2 and 4 are no longer considered duplicates Also, 3 no longer falls back to 4 in case of duplicate, now it goes to 2.

Add Duplicate Costume Fix

---

src/main/java/com/github/nicholasmoser/gnt4/ui/CostumeController.java

Choji's costume 3 and 4 require an additional large Choji costume in order to work, so code was added to check for this. A window will ask if you want to just re-use the existing large Choji model as well.

Add check for large Choji when extending Choji costumes

---

src/main/java/com/github/nicholasmoser/gnt4/seq/comment/Functions.java
src/main/java/com/github/nicholasmoser/gnt4/seq/ext/SeqEdit.java
src/main/java/com/github/nicholasmoser/gnt4/ui/CostumeBranchTableFix.java
src/main/java/com/github/nicholasmoser/gnt4/ui/CostumeController.java
src/test/java/com/github/nicholasmoser/gnt4/seq/SeqKingTest.java

In each SEQ file is a branch table for the costume id. Each branch contains specific physics for that model, such as Temari's sash or the paper bandages on Kisame's sword. Most characters have no physics set for costumes 3 and 4, so physics will be broken for many characters. In cases like Ino, the costume may crash completely if the physics code reference parts of the model that do not exist (such as using a short hair Ino on costume 3 and 4, which expects long hair).
This PR simply writes a SEQ edit to fix the branch table. Easy cases are handled automatically, whereas cases like Ino will ask the user how they want to handle it.

Fix model physics costume table branch

---

src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/gnt4/seq/ext/SeqEditor.java

Fix two issues:
- It is possible in some circumstances for the file entries to be removed from the sqlite database but not added back after building an ISO. After this happens, changes to files will no longer be tracked since it thinks no files exist in the workspace. I've added a fix to the refresh method to check for this and rebuild the database if it is detected.
- Display offset and hijacked byte length in hex since hex is most often used for each value

Fix corrupted databases and display SEQ editor values in hex

---

src/main/java/com/github/nicholasmoser/gnt4/dol/DolHijack.java
src/main/java/com/github/nicholasmoser/gnt4/ui/EyeExtender.java

When creating an workspace from an ISO using the code "Allow Additional Eye Textures", it would error when trying to create the codes.json file. This hack adds a parser for this code, which is extra difficult since it is a dynamic code.
This PR will be followed by a PR that will force codes.json to always be included in the ISO, so that no more hacks like this need to be done.

Add fix for parsing code 'Allow Additional Eye Textures' with no codes.json

---

src/main/java/com/github/nicholasmoser/FPKPacker.java
src/main/java/com/github/nicholasmoser/Workspace.java
src/main/java/com/github/nicholasmoser/gecko/GeckoCodeJSON.java
src/main/java/com/github/nicholasmoser/gnt4/GNT4Workspace.java
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/java/com/github/nicholasmoser/gnt4/dol/DolHijack.java
src/main/java/com/github/nicholasmoser/workspace/SQLiteWorkspaceState.java
src/main/java/com/github/nicholasmoser/workspace/WorkspaceState.java

- If user is not bundling the codes.json file, query them to do so on each build. Otherwise the codes may fail to be parsed when creating new workspaces from the ISO.
- Refresh before each build so that all new file changes are accounted for.

Force bundle codes.json and refresh on build

---

src/main/java/com/github/nicholasmoser/Workspace.java
src/main/java/com/github/nicholasmoser/gnt4/GNT4Workspace.java
src/main/java/com/github/nicholasmoser/gnt4/MenuController.java
src/main/resources/com/github/nicholasmoser/gnt4/menu.fxml

Fixes #150
Originally GNTool would hash every file in the workspace when refreshing. This is very slow, especially on mechanical hard drives. This was replaced with new code that only hash files with a last modified date/time after the last build. This drastically sped up refreshes, but created a problem when you copied a file with a modified date/time in the past. You could not detect this file without manually modifying it to update the modified date/time.
Now, there is both a quick and full refresh option. Full refresh only occurs when requested. When doing a full refresh, any files with modified date/times before the last build will be updated to the current date/time. This is done so that any new quick refreshes will now see this file.

Add ability to do quick refresh and full refresh

---

src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java
src/main/java/com/github/nicholasmoser/gnt4/seq/comment/Comments.java
src/main/java/com/github/nicholasmoser/gnt4/seq/opcodes/ExtraData.java

Itachi in SCON4 has really hacked up string data. Some of the extra data ends earlier than expected and the String Active Strings offsets begin 4 bytes earlier than expected. I've updated the parser to account for this.

String fixes to parse Itachi in SCON4

---

src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java
src/main/java/com/github/nicholasmoser/gnt4/seq/SeqKing.java
src/main/java/com/github/nicholasmoser/gnt4/seq/comment/Comments.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup10.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup12.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup14.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup16.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup1A.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup1E.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup21.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup23.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup38.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup39.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup3A.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup3B.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup3C.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup40.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup41.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup4B.java
src/main/java/com/github/nicholasmoser/gnt4/seq/groups/OpcodeGroup61.java
src/main/java/com/github/nicholasmoser/gnt4/seq/opcodes/ExtraData.java
src/test/java/com/github/nicholasmoser/gnt4/seq/SeqKingTest.java

These changes add support for disassembling the following SEQ files:
- files/maki/charsel4.seq
- files/maki/m_gal.seq
- files/maki/m_nfile.seq
- files/maki/m_nsiki.seq
- files/maki/m_sndplr.seq
- files/maki/m_viewer.seq
- files/stg/001/0000.seq
- files/stg/001/0100.seq
You can find the latest vanilla GNT4 disassembled files here: https://gnt4.online/seq/seqs.html
This PR also adds more code to handle Extra Data sections for SCON4 that are malformed.
Note: This is the first time we've disassembled stage SEQ files, so hopefully we soon should be able to edit stage code!

Add support for disassembling more SEQ files
